### ISSUE TITLE
Strider build errors

### ISSUE THREAD

**Issue by meker12** [deconst/strider-deconst-common#4]
I noticed the following build error in the [Cloud Keep](https://build.developer.rackspace.com/rackerlabs/docs-barbican/) build log.

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ezi9ca7w/pyenchant
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.``

This error shows up in all the build logs:

`You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.``

Doesn't seem to affect the output, but wanted to let @smashwilson know.

**Comment by smashwilson** [comment]
Yeah, this is harmless. At some point I should rebuild the preparer-sphinx container to bring it up to date, but as far as I know it isn't urgent.
